image: cr.genos.nebtex.com/publicdev/golang:1.8

cache:
  key: "$CI_COMMIT_REF_NAME"
  paths:
  - vendor/
  untracked: true

before_script:
  - mkdir -p /go/src /go/bin /go/src/github.com/nebtex
  - export GOPATH=/go
  - export PATH=$PATH:/go/bin
  - ln -s /builds/publicdev/vault-migrator  /go/src/github.com/nebtex/vault-migrator
  - cd /go/src/github.com/nebtex/vault-migrator
  - echo $PWD
  - add-apt-repository ppa:masterminds/glide --yes &&  apt-get update -y
  - apt-get install glide make curl zip unzip -y

stages:
  - deps
  - test
  - build
  - deploy
  - publish
deps:
  stage: deps
  script:
    - glide install

build_master:
  stage: build
  only:
    - master
  script:
    - export VAULT_MIGRATOR_RELEASE=latest
    - make build

build_tags:
  stage: build
  only:
    - tags
  script:
    - export prefix=v
    - export VAULT_MIGRATOR_RELEASE=${CI_COMMIT_TAG#$prefix}
    - make build

deploy:
  stage: deploy
  only:
    - master
  script:
    - curl --request POST --form token=$MENSHEND_TRIGGER_TOKEN --form ref=master https://git.genos.nebtex.com/api/v4/projects/181/trigger/pipeline
